app/Http/routes.php
<?php

/**
 * Frontend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Frontend'], function ()
{
	require(__DIR__ . "/Routes/Frontend/Frontend.php");
	require(__DIR__ . "/Routes/Frontend/Access.php");
});

/**
 * Backend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Backend'], function ()
{
	Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function ()
	{
		/**
		 * These routes need the Administrator Role
		 * or the view-backend permission (good if you want to allow more than one group in the backend, then limit the backend features by different roles or permissions)
		 *
		 * If you wanted to do this in the controller it would be:
		 * $this->middleware('access.routeNeedsRoleOrPermission:{role:Administrator,permission:view_backend,redirect:/,with:flash_danger|You do not have access to do that.}');
		 *
		 * You could also do the above in the Route::group below and remove the other parameters, but I think this is easier to read here.
		 * Note: If you have both, the controller will take precedence.
		 */
		Route::group([
			'middleware' => 'access.routeNeedsRoleOrPermission',
			'role'       => ['Administrator'],
			'permission' => ['view_backend'],
			'redirect'   => '/',
			'with'       => ['flash_danger', 'You do not have access to do that.']
		], function ()
		{
			Route::get('dashboard', ['as' => 'backend.dashboard', 'uses' => 'DashboardController@index']);
			require(__DIR__ . "/Routes/Backend/Access.php");
		});
	});
});

app/Permission.php
<?php namespace App;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Permission
 * @package App
 */
class Permission extends Model {
	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table;

	/**
	 *
	 */
	public function __construct()
	{
		$this->table = config('access.permissions_table');
	}

	/**
	 * Many-to-Many relations with Roles.
	 *
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
	 */
	public function roles()
	{
		return $this->belongsToMany(config('access.role'), config('access.permission_role_table'), 'permission_id', 'role_id');
	}

	/**
	 * Many-to-Many relations with Users.
	 *
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
	 */
	public function users()
	{
		return $this->belongsToMany(config('auth.model'), config('access.permission_user_table'), 'permission_id', 'user_id');
	}

	/**
	 * @return string
	 */
	public function getSystemLabelAttribute() {
		switch($this->system) {
			case 0:
				return '<span class="label label-success">No</span>';

			case 1:
				return '<span class="label label-danger">Yes</span>';
		}
	}

	/**
	 * @return bool
	 */
	public function isSystem() {
		return $this->system == 1 ? true : false;
	}

	/**
	 * @return string
	 */
	public function getEditButtonAttribute() {
		return '<a href="'.route('admin.access.roles.permissions.edit', $this->id).'" class="btn btn-xs btn-primary"><i class="fa fa-pencil" data-toggle="tooltip" data-placement="top" title="Edit"></i></a>';
	}

	/**
	 * @return string
	 */
	public function getDeleteButtonAttribute() {
		return '<a href="'.route('admin.access.roles.permissions.destroy', $this->id).'" class="btn btn-xs btn-danger" data-method="delete"><i class="fa fa-times" data-toggle="tooltip" data-placement="top" title="Delete"></i></a>';
	}

	/**
	 * @return string
	 */
	public function getActionButtonsAttribute() {
		$buttons = '';
		$buttons .= $this->getEditButtonAttribute();

		//If the permission is not a system item it can be deleted
		if (! $this->isSystem()) {
			$buttons .= ' '.$this->getDeleteButtonAttribute();
		}

		return $buttons;
	}

	/**
	 * Before delete all constrained foreign relations.
	 *
	 * @return bool
	 */
	public function beforeDelete()
	{
		DB::table(config('access.permission_role_table'))->where('permission_id', $this->id)->delete();
	}
}

app/Role.php
<?php namespace App;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Role
 * @package App
 */
class Role extends Model {
	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table;

	/**
	 *
	 */
	public function __construct()
	{
		$this->table = config('access.roles_table');
	}

	/**
	 * Many-to-Many relations with Users.
	 *
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
	 */
	public function users()
	{
		return $this->belongsToMany(config('auth.model'), config('access.assigned_roles_table'), 'role_id', 'user_id');
	}

	/**
	 * Many-to-Many relations with Permission.
	 *
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
	 */
	public function permissions()
	{
		return $this->belongsToMany(config('access.permission'), config('access.permission_role_table'), 'role_id', 'permission_id');
	}

	/**
	 * @return string
	 */
	public function getEditButtonAttribute() {
		return '<a href="'.route('admin.access.roles.edit', $this->id).'" class="btn btn-xs btn-primary"><i class="fa fa-pencil" data-toggle="tooltip" data-placement="top" title="Edit"></i></a>';
	}

	/**
	 * @return string
	 */
	public function getDeleteButtonAttribute() {
		if ($this->id != 1) //Cant delete master admin role
			return '<a href="'.route('admin.access.roles.destroy', $this->id).'" class="btn btn-xs btn-danger" data-method="delete"><i class="fa fa-times" data-toggle="tooltip" data-placement="top" title="Delete"></i></a>';
		return '';
	}

	/**
	 * @return string
	 */
	public function getActionButtonsAttribute() {
		return $this->getEditButtonAttribute().' '.$this->getDeleteButtonAttribute();
	}

	/**
	 * Before delete all constrained foreign relations
	 *
	 * @return bool
	 */
	public function beforeDelete()
	{
		DB::table(config('access.assigned_roles_table'))->where('role_id', $this->id)->delete();
		DB::table(config('access.permission_role_table'))->where('role_id', $this->id)->delete();
	}

	/**
	 * Save the inputted permissions.
	 *
	 * @param mixed $inputPermissions
	 *
	 * @return void
	 */
	public function savePermissions($inputPermissions)
	{
		if (! empty($inputPermissions)) {
			$this->permissions()->sync($inputPermissions);
		} else {
			$this->permissions()->detach();
		}
	}

	/**
	 * Attach permission to current role.
	 *
	 * @param object|array $permission
	 *
	 * @return void
	 */
	public function attachPermission($permission)
	{
		if (is_object($permission)) {
			$permission = $permission->getKey();
		}

		if (is_array($permission)) {
			$permission = $permission['id'];
		}

		$this->permissions()->attach($permission);
	}

	/**
	 * Detach permission form current role.
	 *
	 * @param object|array $permission
	 *
	 * @return void
	 */
	public function detachPermission($permission)
	{
		if (is_object($permission))
			$permission = $permission->getKey();

		if (is_array($permission))
			$permission = $permission['id'];

		$this->permissions()->detach($permission);
	}

	/**
	 * Attach multiple permissions to current role.
	 *
	 * @param mixed $permissions
	 *
	 * @return void
	 */
	public function attachPermissions($permissions)
	{
		foreach ($permissions as $permission) {
			$this->attachPermission($permission);
		}
	}

	/**
	 * Detach multiple permissions from current role
	 *
	 * @param mixed $permissions
	 *
	 * @return void
	 */
	public function detachPermissions($permissions)
	{
		foreach ($permissions as $permission) {
			$this->detachPermission($permission);
		}
	}
}

app/Http/Controllers/Backend/Access/PermissionController.php
<?php namespace App\Http\Controllers\Backend\Access;

use App\Http\Controllers\Controller;
use App\Repositories\Backend\Role\RoleRepositoryContract;
use App\Repositories\Backend\Permission\PermissionRepositoryContract;
use App\Http\Requests\Backend\Access\Permission\CreatePermissionRequest;
use App\Http\Requests\Backend\Access\Permission\UpdatePermissionRequest;

/**
 * Class PermissionController
 * @package App\Http\Controllers\Access
 */
class PermissionController extends Controller {

	/**
	 * @var RoleRepositoryContract
	 */
	protected $roles;
	/**
	 * @var PermissionRepositoryContract
	 */
	protected $permissions;

	/**
	 * @param RoleRepositoryContract $roles
	 * @param PermissionRepositoryContract $permissions
	 */
	public function __construct(
		RoleRepositoryContract $roles,
		PermissionRepositoryContract $permissions) {
		$this->roles = $roles;
		$this->permissions = $permissions;
	}

	/**
	 * @return mixed
	 */
	public function index() {
		return view('backend.access.roles.permissions.index')
			->withPermissions($this->permissions->getPermissionsPaginated(50));
	}

	/**
	 * @return mixed
	 */
	public function create() {
		return view('backend.access.roles.permissions.create')
			->withRoles($this->roles->getAllRoles());
	}

	/**
	 * @param CreatePermissionRequest $request
	 * @return mixed
	 */
	public function store(CreatePermissionRequest $request) {
		$this->permissions->create($request->except('permission_roles'), $request->only('permission_roles'));
		return redirect()->route('admin.access.roles.permissions.index')->withFlashSuccess("Permission successfully created.");
	}

	/**
	 * @param $id
	 * @return mixed
	 */
	public function edit($id) {
		$permission = $this->permissions->findOrThrowException($id, true);
		return view('backend.access.roles.permissions.edit')
			->withPermission($permission)
			->withPermissionRoles($permission->roles->lists('id')->all())
			->withRoles($this->roles->getAllRoles());
	}

	/**
	 * @param $id
	 * @param UpdatePermissionRequest $request
	 * @return mixed
	 */
	public function update($id, UpdatePermissionRequest $request) {
		$this->permissions->update($id, $request->except('permission_roles'), $request->only('permission_roles'));
		return redirect()->route('admin.access.roles.permissions.index')->withFlashSuccess("Permission successfully updated.");
	}

	/**
	 * @param $id
	 * @return mixed
	 */
	public function destroy($id) {
		$this->permissions->destroy($id);
		return redirect()->route('admin.access.roles.permissions.index')->withFlashSuccess("Permission successfully deleted.");
	}
}

app/Http/Controllers/Backend/Access/RoleController.php
<?php namespace App\Http\Controllers\Backend\Access;

use App\Http\Controllers\Controller;
use App\Repositories\Backend\Role\RoleRepositoryContract;
use App\Repositories\Backend\Permission\PermissionRepositoryContract;
use App\Http\Requests\Backend\Access\Role\CreateRoleRequest;
use App\Http\Requests\Backend\Access\Role\UpdateRoleRequest;

/**
 * Class RoleController
 * @package App\Http\Controllers\Access
 */
class RoleController extends Controller {

	/**
	 * @var RoleRepositoryContract
	 */
	protected $roles;
	/**
	 * @var PermissionRepositoryContract
	 */
	protected $permissions;

	/**
	 * @param RoleRepositoryContract $roles
	 * @param PermissionRepositoryContract $permissions
	 */
	public function __construct(
		RoleRepositoryContract $roles,
		PermissionRepositoryContract $permissions) {
		$this->roles = $roles;
		$this->permissions = $permissions;
	}

	/**
	 * @return mixed
	 */
	public function index() {
		return view('backend.access.roles.index')
			->withRoles($this->roles->getRolesPaginated(50));
	}

	/**
	 * @return mixed
	 */
	public function create() {
		return view('backend.access.roles.create')
			->withPermissions($this->permissions->getPermissionsNotAssociatedWithUser());
	}

	/**
	 * @param CreateRoleRequest $request
	 * @return mixed
	 */
	public function store(CreateRoleRequest $request) {
		$this->roles->create($request->except('role_permissions'), $request->only('role_permissions'));
		return redirect()->route('admin.access.roles.index')->withFlashSuccess('The role was successfully created.');
	}

	/**
	 * @param $id
	 * @return mixed
	 */
	public function edit($id) {
		$role = $this->roles->findOrThrowException($id, true);
		return view('backend.access.roles.edit')
			->withRole($role)
			->withRolePermissions($role->permissions->lists('id')->all())
			->withPermissions($this->permissions->getPermissionsNotAssociatedWithUser());
	}

	/**
	 * @param $id
	 * @param UpdateRoleRequest $request
	 * @return mixed
	 */
	public function update($id, UpdateRoleRequest $request) {
		$this->roles->update($id, $request->except('role_permissions'), $request->only('role_permissions'));
		return redirect()->route('admin.access.roles.index')->withFlashSuccess('The role was successfully updated.');
	}

	/**
	 * @param $id
	 * @return mixed
	 */
	public function destroy($id) {
		$this->roles->destroy($id);
		return redirect()->route('admin.access.roles.index')->withFlashSuccess('The role was successfully deleted.');
	}
}

resources/views/backend/access/roles/permissions/create.blade.php
@extends ('backend.layouts.master')

@section ('title', 'Permission Management | Create Permission')

@section ('before-styles-end')
    {!! HTML::style('css/plugin/jquery.onoff.css') !!}
@stop

@section('page-header')
    <h1>
        User Management
        <small>Create Permission</small>
    </h1>
@endsection

@section ('breadcrumbs')
    <li><a href="{!!route('backend.dashboard')!!}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
    <li>{!! link_to_route('admin.access.users.index', 'User Management') !!}</li>
    <li>{!! link_to_route('admin.access.roles.permissions.index', 'Permission Management') !!}</li>
    <li>{!! link_to_route('admin.access.roles.permissions.create', 'Create Permission') !!}</li>
@stop

@section('content')

    @include('backend.access.includes.partials.header-buttons')

    {!! Form::open(['route' => 'admin.access.roles.permissions.store', 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'post']) !!}

        <div class="form-group">
            <label class="col-lg-2 control-label">Permission Name</label>
            <div class="col-lg-10">
                {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Permission Name']) !!}
            </div>
        </div><!--form control-->

        <div class="form-group">
            <label class="col-lg-2 control-label">Display Name</label>
            <div class="col-lg-10">
                {!! Form::text('display_name', null, ['class' => 'form-control', 'placeholder' => 'Display Name']) !!}
            </div>
        </div><!--form control-->

        <div class="form-group">
            <label class="col-lg-2 control-label">System Permission?</label>
            <div class="col-lg-3">
                <div class="system-permission-switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="system" class="toggleBtn onoffswitch-checkbox" id="system">
                        <label for="system" class="onoffswitch-label">
                            <div class="onoffswitch-inner"></div>
                            <div class="onoffswitch-switch"></div>
                        </label>
                    </div>
                </div><!--blue checkbox-->
            </div>
        </div><!--form control-->

        <div class="form-group">
            <label class="col-lg-2 control-label">Associated Roles</label>
            <div class="col-lg-3">
                @if (count($roles) > 0)
                    @foreach($roles as $role)
                        {!! $role->name !!}
                        <div class="create-permissions-switch">
                            <div class="onoffswitch">
                                <input type="checkbox" {{$role->id == 1 && Config::get('access.roles.administrator_forced') ? "disabled='disabled' checked='checked'" : ''}} value="{{$role->id}}" name="permission_roles[]" class="toggleBtn onoffswitch-checkbox" id="role-{{$role->id}}">
                                <label for="role-{{$role->id}}" class="onoffswitch-label">
                                    <div class="onoffswitch-inner"></div>
                                    <div class="onoffswitch-switch"></div>
                                </label>
                            </div>
                        </div><!--green checkbox-->
                        <div class="clearfix"></div>
                    @endforeach
                @else
                    No Roles to set
                @endif

                @if (Config::get('access.roles.administrator_forced'))
                    {!! Form::hidden('permission_roles[]', 1) !!}
                @endif
            </div>
        </div><!--form control-->

        <div class="pull-left">
            <a href="{{route('admin.access.roles.permissions.index')}}" class="btn btn-danger">Cancel</a>
        </div>

        <div class="pull-right">
            <input type="submit" class="btn btn-success" value="Save" />
        </div>
        <div class="clearfix"></div>

    {!! Form::close() !!}
@stop

resources/views/backend/access/roles/permissions/edit.blade.php
@extends ('backend.layouts.master')

@section ('title', 'Permission Management | Edit Permission')

@section ('before-styles-end')
    {!! HTML::style('css/plugin/jquery.onoff.css') !!}
@stop

@section('page-header')
    <h1>
        User Management
        <small>Edit Permission</small>
    </h1>
@endsection

@section ('breadcrumbs')
    <li><a href="{!!route('backend.dashboard')!!}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
    <li>{!! link_to_route('admin.access.users.index', 'User Management') !!}</li>
    <li>{!! link_to_route('admin.access.roles.permissions.index', 'Permission Management') !!}</li>
    <li>{!! link_to_route('admin.access.roles.permissions.edit', 'Edit '.$permission->display_name, $permission->id) !!}</li>
@stop

@section('content')

    @include('backend.access.includes.partials.header-buttons')

    {!! Form::model($permission, ['route' => ['admin.access.roles.permissions.update', $permission->id], 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'PATCH']) !!}

        <div class="form-group">
            <label class="col-lg-2 control-label">Permission Name</label>
            <div class="col-lg-10">
                <input type="text" name="name" class="form-control" placeholder="Permission Name" {{$permission->system == 1 ? 'readonly="readonly"' : ''}} value="{{$permission->name}}" />
            </div>
        </div><!--form control-->

        <div class="form-group">
            <label class="col-lg-2 control-label">Display Name</label>
            <div class="col-lg-10">
                {!! Form::text('display_name', null, ['class' => 'form-control', 'placeholder' => 'Display Name']) !!}
            </div>
        </div><!--form control-->

        <div class="form-group">
            <label class="col-lg-2 control-label">System Permission?</label>
            <div class="col-lg-3">
                <div class="system-permission-switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="system" {{$permission->system == 1 ? 'checked="checked"' : ''}} class="toggleBtn onoffswitch-checkbox" id="system">
                        <label for="system" class="onoffswitch-label">
                            <div class="onoffswitch-inner"></div>
                            <div class="onoffswitch-switch"></div>
                        </label>
                    </div>
                </div><!--blue checkbox-->
            </div>
        </div><!--form control-->

        <div class="form-group">
            <label class="col-lg-2 control-label">Associated Roles</label>
            <div class="col-lg-3">
                @if (count($roles) > 0)
                    @foreach($roles as $role)
                    {!! $role->name !!}
                    <div class="create-permissions-switch">
                        <div class="onoffswitch">
                            <input type="checkbox" {{$role->id == 1 && Config::get('access.roles.administrator_forced') ? "disabled='disabled'" : ''}} {{in_array($role->id, $permission_roles) || ($role->id == 1 && Config::get('access.roles.administrator_forced')) ? 'checked="checked"' : ""}} value="{{$role->id}}" name="permission_roles[]" class="toggleBtn onoffswitch-checkbox" id="role-{{$role->id}}">
                            <label for="role-{{$role->id}}" class="onoffswitch-label">
                                <div class="onoffswitch-inner"></div>
                                <div class="onoffswitch-switch"></div>
                            </label>
                        </div>
                    </div><!--green checkbox-->
                    <div class="clearfix"></div>
                    @endforeach
                @else
                    No Roles to set
                @endif

                @if (Config::get('access.roles.administrator_forced'))
                    {!! Form::hidden('permission_roles[]', 1) !!}
                @endif
            </div>
        </div><!--form control-->

        <div class="pull-left">
            <a href="{{route('admin.access.roles.permissions.index')}}" class="btn btn-danger">Cancel</a>
        </div>

        <div class="pull-right">
            <input type="submit" class="btn btn-success" value="Update" />
        </div>
        <div class="clearfix"></div>

    {!! Form::close() !!}
@stop

resources/views/backend/access/roles/permissions/index.blade.php
@extends ('backend.layouts.master')

@section ('title', 'Permission Management')

@section('page-header')
    <h1>
        User Management
        <small>Permission Management</small>
    </h1>
@endsection

@section ('breadcrumbs')
    <li><a href="{!!route('backend.dashboard')!!}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
    <li>{!! link_to_route('admin.access.users.index', 'User Management') !!}</li>
    <li>{!! link_to_route('admin.access.roles.permissions.index', 'Permission Management') !!}</li>
@stop

@section('content')
    @include('backend.access.includes.partials.header-buttons')

    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr>
            <th>Permission</th>
            <th>Name</th>
            <th>Users</th>
            <th>Roles</th>
            <th>System?</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
            @foreach ($permissions as $permission)
            <tr>
                <td>{!! $permission->name !!}</td>
                <td>{!! $permission->display_name !!}</td>
                <td>
                    @if (count($permission->users))
                        @foreach($permission->users as $user)
                            {!! $user->name !!}<br/>
                        @endforeach
                    @else
                        None
                    @endif
                </td>
                <td>
                    @if (count($permission->roles))
                        @foreach($permission->roles as $role)
                            {!! $role->name !!}<br/>
                        @endforeach
                    @else
                        None
                    @endif
                </td>
                <td>{!! $permission->system_label !!}</td>
                <td>{!! $permission->action_buttons !!}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="pull-left">
        {{ $permissions->total() }} permissions(s) total
    </div>

    <div class="pull-right">
        {{ $permissions->render() }}
    </div>

    <div class="clearfix"></div>
@stop